# Generated by Django 4.0.6 on 2022-07-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_dogs', '0002_post_alterado_post_criado_post_publicado_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tiulo',
            new_name='titulo',
        ),
    ]
